# Generated by Django 4.0 on 2022-01-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='cat/')),
                ('url', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('Post_title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='cat/')),
                ('url', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
    ]
