# Generated by Django 4.0 on 2022-01-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_read_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverpic', models.ImageField(upload_to='about/')),
                ('bio', models.TextField()),
            ],
        ),
    ]
